# Generated by Django 5.2.6 on 2025-09-15 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Football Shoes'), ('ball', 'Football'), ('equipment', 'Training Equipment'), ('accessories', 'Accessories')], default='accessories', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
