# Generated by Django 5.2.6 on 2025-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Football Shoes'), ('ball', 'Football'), ('equipment', 'Training Equipment'), ('accessories', 'Accessories')], default='accessories', max_length=20),
        ),
    ]
